apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
      - name: web
        image: localhost:5000/devsecops-demo:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo
spec:
  type: NodePort
  selector:
    app: devsecops-demo
  ports:
  - port: 80
    nodePort: 30080
